### ISSUE TITLE
Gendered proverbs suggestions

### ISSUE THREAD

**Issue by ohnx** [wooorm/retext-equality#17]
In the lines [here](https://github.com/wooorm/retext-equality/blob/master/lib/patterns.json#L2831-L2857), "ladylike" and "like a man" are said to be inconsiderate, which totally makes sense.

However, the suggestions to fix these words are completely outrageous. Why on earth does a program that is *made to promote equality for everyone* contain suggestions that "ladylike" should be replaced with "cultured"? Is this some sort of subversive way to suggest that ladies should be cultured?

This problem also exists with the "like a man" suggesting "bravely". Is the program implying that men should be brave?

I just thought I'd bring this point to attention as these suggestions really seem to lower the quality of the program and may make people think that the program is not actually promoting social equality :)

**Comment by wooorm** [comment]
What suggestions do you suggest?
I think it's best to, on these suggestions, focus on what most people actually intend with those words: people using the word "ladylike" don't mean people who have those genitals, they mean people who are "cultured" and the like (which I got from a thesaurus). this tool proposes synonyms, so why shouldn't it provide synonyms?

**Comment by ohnx** [comment]
Ideally, there would be no suggestions, simply saying to reconsider those words. :)

However, since it is meant for there to be suggestions, I suppose those words are the only way.
