### ISSUE TITLE
mental disorders are not adjectives

### ISSUE THREAD

**Issue by yoshuawuyts** [wooorm/retext-equality#4]
My partner pointed this out to me, I think it's quite striking:
![mental disorders are not adjectives](http://2.bp.blogspot.com/-gzqxRGoLAhE/U_EM26KCKnI/AAAAAAAAAWo/njZLSSI4mjU/s1600/IMG_6582.JPG)

Think we could do something to catch this.

**Comment by wooorm** [comment]
Nice :+1:! I did a lot of work for this in the [last three commits](https://github.com/wooorm/retext-equality/commits/ef25413e789e0232cdd458c6d93a525aefe9cae8), just found a bug in `bipolar`, and I’ll add the insomnia/ocd/anorexic too
